### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: corsheaders

### ISSUE THREAD

**Issue by stirringhalo** [boundlessgeo/exchange#109]
When starting to build a dev environment, following almost all the instructions in the docker/Readme.rst (trying both the harts- and this repo) but not switching to the docker branch (as it's no different in harts), I ran into similar issues like:

django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: corsheaders

I have been cleaning the images, containers, volumes and network each time I try a different repo.

Could you confirm the steps for getting a work environment with exchange going? Are you all using vagrant?

**Comment by travislbrundage** [comment]
This is due to the latest GeoNode - if you're trying to point to GeoNode master, it will cause this break. However, Exchange is pointing to 2.5.5 currently and works fine.

Check the `requirements.txt` file has `geonode==2.5.5` ... if you're like me and were pointing to GeoNode master to fiddle with GeoNode within Exchange, having this line will currently break it: `-e git+git://github.com/GeoNode/geonode@master#egg=geonode`

**Comment by stirringhalo** [comment]
Great, thanks, I'll give that a try!

**Comment by sarasafavi** [comment]
Re-opened at https://github.com/boundlessgeo/exchange/issues/113 for tracking purposes
